# Generated by Django 3.2.3 on 2021-06-06 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210606_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='power',
            new_name='max_fps',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='power',
            new_name='max_fps',
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='power',
            new_name='max_fps',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='power',
            new_name='max_fps',
        ),
        migrations.RenameField(
            model_name='psu',
            old_name='power',
            new_name='max_fps',
        ),
        migrations.RenameField(
            model_name='ssd',
            old_name='power',
            new_name='max_fps',
        ),
    ]
